---
- name: Launch ec2 automation_runner instance
  ec2:
    key_name: "{{ key_name }}"
    group: "{{ pulp_sg }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami_auto_runner }}"
    wait: true
    region: "{{ region }}"
    monitoring: no
    assign_public_ip: no
    instance_tags:
      Name: "{{ automation_name }}_automation_runner" 
    count_tag:
      Name: "{{ automation_name }}_automation_runner" 
    exact_count: 1
  register: ec2
- name: Add new instance to host group
  add_host: hostname={{ item.public_ip }} groupname=launched
  with_items: ec2.instances
- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances
