---
- name: setup repos for stable pulp in Fedora 22
  shell: "echo -e '[pulp-stable]\n
  name=Pulp Production Releases\n
  baseurl=https://repos.fedorapeople.org/repos/pulp/pulp/stable/latest/fedora-21/$basearch/\n
  enabled=1\n
  skip_if_unavailable=1\n
  gpgcheck=0' > /etc/yum.repos.d/fedora-pulp.repo"
  when: "ansible_distribution=='Fedora' and ansible_distribution_version|int==22"
- name: setup repos for stable pulp in Fedora < 22
  shell: "echo -e '[pulp-stable]\n
  name=Pulp Production Releases\n
  baseurl=https://repos.fedorapeople.org/repos/pulp/pulp/stable/latest/fedora-$releasever/$basearch/\n
  enabled=1\n
  skip_if_unavailable=1\n
  gpgcheck=0' > /etc/yum.repos.d/fedora-pulp.repo"
  when: "ansible_distribution=='Fedora' and ansible_distribution_version|int<22"
- name: setup repos for stable pulp in redhat
  shell: "echo -e '[pulp-stable]\n
  name=Pulp Production Releases\n
  baseurl=https://repos.fedorapeople.org/repos/pulp/pulp/stable/latest/$releasever/$basearch/\n
  enabled=1\n
  skip_if_unavailable=1\n
  gpgcheck=0' > /etc/yum.repos.d/rhel-pulp.repo"
  when: "ansible_distribution=='RedHat'"
