---
- name: install necessary packages
  action: "{{package_manager}} name={{ item }} state=present"
  with_items:
    - git
    - tito
    - make
    - python-sphinx
    - python2-devel
    - selinux-policy-devel
    - createrepo
    - s3cmd
- name: remove previous source files
  file: path=/tmp/{{item}} state=absent
  with_items: "{{repos_list}}"
- name: checkout git repositories 
  git: repo=https://github.com/pulp/{{item}} dest=/tmp/{{item}} version={{tested_version}}-{{tested_branch}}
  with_items: "{{ repos_list }}"

- name: delete previously built rpms
  file: path={{reposerver_repo_dir}} state=absent

- name: create rpms from them
  command: "{{ item[1] }} chdir=/tmp/{{ item[0] }}"
  with_nested:
    - "{{ repos_list }}"
    - ['tito init', 'tito build --test --rpm -o {{ reposerver_repo_dir }}']
- name: create repository from previously built rpm's
  command: createrepo {{ reposerver_repo_dir }}/noarch

- name: delete content from repo 'current'
  command: "s3cmd rm --recursive s3://{{bucket_name}}/current/"

- name: get date and time
  command: "date '+%y-%m-%d-%H-%M'"
  register: current_date

- name: upload packages for archiving
  shell: "s3cmd put --recursive /{{reposerver_repo_dir}}/noarch/ s3://{{bucket_name}}/{{current_date.stdout}}/repo/noarch/"

- name: copy packages to repo 'current'
  shell: "s3cmd cp --recursive s3://{{bucket_name}}/{{current_date.stdout}}/repo/noarch/ s3://{{bucket_name}}/current/repo/noarch/"

- name: get list of previously built packages
  shell: find {{reposerver_repo_dir}}/noarch -name '*.rpm' -printf '%f\n' |sed 's/\([a-z\-]\)-[0-9].*/\1\*/'|tr '\n' ' '
  register: excluded_packages

- name: create s3 repository file for FEDORA
  shell: "echo -e '[Pulp-{{tested_version}}-{{tested_branch}}]\n
  name=Pulp-{{tested_version}} nightbuild s3 repo\n
  baseurl=http://s3-{{region}}.amazonaws.com/{{bucket_name}}/current/repo/noarch\n
  gpgcheck=0\n
  enabled=1\n\n' > fedora-pulp-s3.repo"
- name: modify official FEDORA pulp repository file to exclude built packages
  shell: "echo -e '[Pulp-{{tested_version}}-beta]\n
  name=Pulp v2 Beta Builds\n
#  baseurl=http://repos.fedorapeople.org/repos/pulp/pulp/beta/{{tested_version}}/fedora-$releasever/$basearch/\n
  baseurl=http://repos.fedorapeople.org/repos/pulp/pulp/beta/{{tested_version}}/fedora-21/$basearch/\n
  enabled=1\n
  skip_if_unavailable=1\n
  gpgcheck=0\n
  exclude={{excluded_packages.stdout}}' > fedora-pulp-s3.repo"
  

- name: create s3 repository file for RHEL
  shell: "echo -e '[Pulp-{{tested_version}}-{{tested_branch}}]\n
  name=Pulp-{{tested_version}} nightbuild s3 repo\n
  baseurl=http://s3-{{region}}.amazonaws.com/{{bucket_name}}/current/repo/noarch\n
  gpgcheck=0\n
  enabled=1\n\n' > rhel-pulp-s3.repo"
- name: modify official RHEL pulp repository file to exclude built packages
  shell: "echo -e '[Pulp-{{tested_version}}-beta]\n
  name=Pulp v2 Beta Builds\n
  baseurl=http://repos.fedorapeople.org/repos/pulp/pulp/beta/{{tested_version}}/$releasever/$basearch/\n
  enabled=1\n
  skip_if_unavailable=1\n
  gpgcheck=0\n
  exclude={{excluded_packages.stdout}}' >> rhel-pulp-s3.repo"



- name: build documentation 
  command: "chdir=/tmp/{{item[0]}}/docs {{item[1]}}"
  with_nested:
    - "{{ repos_list }}"
    - ['make clean', 'make html']
- name: Create a index file for documentation
  template: src=index.j2 dest=./index.html
  


- name: copy docs to s3
  shell: "s3cmd put --recursive /tmp/{{item}}/docs/_build/html/ s3://{{bucket_name}}/{{current_date.stdout}}/docs/{{item}}/"
  with_items:
    - "{{ repos_list }}"
- name: copy index file to s3 bucket
  shell: "s3cmd put ./index.html s3://{{bucket_name}}/{{current_date.stdout}}/docs/" 
- name: copy repo files to s3 as well
  shell: "s3cmd put {{item}} s3://{{bucket_name}}/{{current_date.stdout}}/data/"
  with_items:
    - fedora-pulp-s3.repo
    - rhel-pulp-s3.repo



- name: copy documents also to 'current'
  shell: "s3cmd cp --recursive s3://{{bucket_name}}/{{current_date.stdout}}/docs/ s3://{{bucket_name}}/current/docs/"
- name: copy index file to current
  shell: "s3cmd cp s3://{{bucket_name}}/{{current_date.stdout}}/docs/index.html s3://{{bucket_name}}/current/docs/index.html"
- name: and copy repo files to current
  shell: "s3cmd cp s3://{{bucket_name}}/{{current_date.stdout}}/data/{{item}} s3://{{bucket_name}}/current/data/{{item}}"
  with_items:
    - fedora-pulp-s3.repo
    - rhel-pulp-s3.repo



- name: save link to documents to links.txt
  shell: "echo 'http://s3-{{region}}.amazonaws.com/{{bucket_name}}/current/docs/index.html' >> links.txt"
- name: save link to repo also
  shell: "echo 'http://s3-{{region}}.amazonaws.com/{{bucket_name}}/current/data/{{item}}' >> links.txt"
  with_items:
    - fedora-pulp-s3.repo
    - rhel-pulp-s3.repo

- name: copy files to localhost
  fetch: src={{item}} dest=./ flat=yes
  with_items:
  - links.txt
