---
- name: stop all pulp related services
  service: state=stopped name={{item}}
  with_items:
    - httpd
    - pulp_workers
    - pulp_worker-0
    - pulp_celerybeat
    - pulp_resource_manager
    - qpidd
- name: drop old pulp db
  command: mongo pulp_database --eval "db.dropDatabase()"
- name: start qpid
  service: name=qpidd state=started
- name: manage mongodb
  become: yes
  become_user: apache
  command: pulp-manage-db
- name: start again all pulp related services
  service: state=started name={{item}}
  with_items:
    - httpd
    - pulp_workers
    - pulp_worker-0
    - pulp_celerybeat
    - pulp_resource_manager
