---
- name: Deploy reposerver
  hosts: localhost
  roles:
    - reposerver-deploy

- name: Enable root access on new machine
  remote_user: "{{rem_user_reposerver}}"
  hosts: launched
  tasks:
    - name: Enable root access
      become: yes
      become_method: sudo
      shell: "{{item}}"
      with_items:
        - "sed -i s,disable_root:.*,disable_root:0, /etc/cloud/cloud.cfg"
        - "cat ~{{rem_user_reposerver}}/.ssh/authorized_keys > /root/.ssh/authorized_keys"

- name: Update packages
  hosts: launched
  roles:
    - set-package-manager
  tasks:
    - name: update packages
      action: "{{package_manager}} name=* state=latest"
