---
- name: Launch ec2 single node testing instance
  ec2:
    key_name: "{{ key_name }}"
    group: "{{ pulp_sg }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami_single_node }}"
    wait: true
    region: "{{ region }}"
    monitoring: no
    assign_public_ip: no
    instance_tags:
      Name: "{{automation_name}}_single_node" 
    count_tag:
      Name: "{{automation_name}}_single_node" 
    exact_count: 1
    user_data: |
      "#!/bin/sh
      sed -i s,disable_root:.*,disable_root:0, /etc/cloud/cloud.cfg
      cat ~fedora/.ssh/authorized_keys > /root/.ssh/authorized_keys
      cat ~ec2-user/.ssh/authorized_keys >> /root/.ssh/authorized_keys"
  register: ec2
- name: Add new instance to host group
  add_host: hostname={{ item.public_ip }} groupname=launched
  with_items: ec2.instances
- name: some debug
  debug: var=ec2
- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances

