---
- name: install epel repo
  action: "{{package_manager}} name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_version|int}}.noarch.rpm state=present"
  when: "ansible_distribution=='RedHat'"
- name: install necessarry packages
  action: "{{package_manager}} name={{ item }} state=present"
  with_items:
    - git
    - python-pip
    - python-devel
    - m2crypto
    - python-crypto
    - gcc
    - dnf
    - libxslt-devel
- pip: name=gevent state=present chdir={{automation_dir}}
- pip: name=stitches state=present chdir={{automation_dir}}
- name: generate key for communicating with hosts
  command: "ssh-keygen -f /root/.ssh/test_rsa -N ''"
