---
- name: install epel repo
  action: "{{package_manager}} name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_version|int}}.noarch.rpm state=present"
  when: "ansible_distribution=='RedHat'"
